[tool.black]
line_length = 130
# Target oldest supported Python version
target_version = ["py38"]

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 130
extra_standard_library = [
    "typing_extensions",
    "_typeshed",
    # Extra modules not recognized by isort
    "_compression",
    "_csv",
    "_curses",
    "_markupbase",
    "_random",
    "_weakrefset",
    "genericpath",
    "opcode",
    "pyexpat",
    # Python 2 modules
    "__builtin__",
    "cookielib",
    "cStringIO",
    "httplib",
    "mimetools",
    "rfc822",
    "thread",
    "urllib2",
    "urlparse",
    "BaseHTTPServer",
    "Queue",
    "SimpleHTTPServer",
    "SocketServer",
    "StringIO",
    "UserDict",
    "UserList",
    "UserString",
]
skip = [ # TODO
    "stubs/networkx",
    "stubs/scipy-stubs",
    "stubs/skimage",
    "stubs/sklearn",
    "stubs/transformers-stubs/models/auto",
    "stubs/vispy",
    "utils",
]

[tool.pyright]
# Target oldest supported Python version
pythonversion = "3.8"
typeCheckingMode = "basic"
# Partial stubs are acceptable
reportUnknownArgumentType = false
# Stubs-only packages are fine for testing
reportMissingModuleSource = false
# Error reports to fix in code
reportGeneralTypeIssues = "warning" # TODO
reportMissingImports = "warning" # TODO
reportUnusedVariable = "warning" # TODO
reportUndefinedVariable = "warning" # TODO
# TODO, These files have errors with no code and must be fixed
exclude = [
    "stubs/sklearn/externals/_packaging/version.pyi",
    "stubs/vispy/visuals/isosurface.pyi",
    "stubs/vispy/visuals/mesh.pyi",
    "stubs/vispy/visuals/surface_plot.pyi",
    "stubs/vispy/visuals/transforms/transform_system.pyi",
]

[tool.mypy]
# Target oldest supported Python version
python_version = "3.8"
# Import discovery
namespace_packages = false
ignore_missing_imports = true
# Allow dynamic typing
disallow_any_unimported = false # TODO
disallow_any_expr = false # TODO
disallow_any_decorated = false # TODO
disallow_any_explicit = false # TODO
disallow_any_generics = false # TODO
disallow_subclassing_any = false # TODO
# Untyped definitions and calls
disallow_untyped_calls = false # TODO
disallow_untyped_decorators = true # TODO
disallow_untyped_defs = false # TODO
disallow_incomplete_defs = false # TODO
check_untyped_defs = true
# Configuring warnings
warn_redundant_casts = true
warn_unused_ignores = false # Change from pandas
# Suppressing errors
disable_error_code = [ # TODO
    "arg-type",
    "assignment",
    "attr-defined",
    "misc",
    "name-defined",
    "no-redef",
    "operator",
    "override",
    "return",
    "truthy-function",
    "valid-type",
    "var-annotated",
]
# Configuring error messages
show_column_numbers = true
